version: '3'
services:
  redis:
    image: redis:latest
    restart: always
  db:
    image: postgres:10
    restart: always
    volumes:
      - ./docker/shared/pgdata:/var/lib/postgresql/data
      - ./deploy/conf/postgres_password:/run/secrets/password
    environment:
      POSTGRES_USER: vcweb
      POSTGRES_PASSWORD_FILE: /run/secrets/password
      POSTGRES_DB: vcweb
  django:
    restart: always
    volumes:
      - .:/code
      - ./deploy/conf/config.ini:/secrets/config.ini
      - ./docker/shared:/shared
    environment:
      DJANGO_SETTINGS_MODULE: 'vcweb.settings.dev'
      LANG: "C.UTF-8"
    depends_on:
      - db
      - redis
