# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 16:29


import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_experiment_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentgroup',
            name='experiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_set', to='core.Experiment'),
        ),
        migrations.AlterField(
            model_name='experimentmetadata',
            name='about_url',
            field=models.URLField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experimentmetadata',
            name='logo_url',
            field=models.URLField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experimentmetadata',
            name='namespace',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(b'^[\\w_-]*$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='institution',
            name='cas_server_url',
            field=models.URLField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='institution',
            name='url',
            field=models.URLField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roundconfiguration',
            name='round_type',
            field=models.CharField(choices=[(b'WELCOME', 'Initial welcome page'), (b'GENERAL_INSTRUCTIONS', 'General introduction'), (b'REGULAR', 'Regular experiment round'), (b'CHAT', 'Communication round'), (b'DEBRIEFING', 'Debriefing round summary'), (b'INSTRUCTIONS', 'Instructions'), (b'PRIVATE_PRACTICE', 'Private practice round'), (b'PRACTICE', 'Group practice round'), (b'QUIZ', 'Quiz round'), (b'SURVEY', 'Survey round')], default=b'REGULAR', max_length=32),
        ),
        migrations.AlterField(
            model_name='roundconfiguration',
            name='sequence_number',
            field=models.PositiveIntegerField(help_text='1-based ascending sequence number used to determine experiment round order, e.g., 1,2,3,4,5.'),
        ),
        migrations.AlterField(
            model_name='roundconfiguration',
            name='survey_url',
            field=models.URLField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
