# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-25 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20181116_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='can_receive_invitations',
            field=models.BooleanField(default=False, help_text='Check this box to opt-in and receive email invitations for upcoming experiments'),
        ),
    ]
