
<div class='harvest-table'>
<h3>Maximum harvest table</h3>
<table>
	<thead>
	<tr><th>Current resource level</th><th>Maximum individual harvest level</th></tr>
	</thead>
	<tbody>
	<tr class='harvest-5'><td>25-100</td><td>5</td></tr>
	<tr class='harvest-4'><td>20-24</td><td>4</td></tr>
	<tr class='harvest-3'><td>15-19</td><td>3</td></tr>
	<tr class='harvest-2'><td>10-14</td><td>2</td></tr>
	<tr class='harvest-1'><td>5-9</td><td>1</td></tr>
	<tr class='harvest-0'><td>0-4</td><td>0</td></tr>
	</tbody>
</table>
</div>